[TEST] Fix syntax errors introduced by previous patch
LogicalDisk - 01_disk.py: FAIL
  File "01_disk.py", line 63
    else if dev.Name != test_dev:
          ^
SyntaxError: invalid syntax

Memory - 01_memory.py: FAIL
  File "01_memory.py", line 62
    else if dev.ConsumableBlocks > dev.NumberOfBlocks:
          ^
SyntaxError: invalid syntax

Signed-off-by: Eduardo Lima (Etrunko) <eblima@br.ibm.com>