Remove extranous or unnecessary parameter from error messages
Testing on a system failed with:

Profile - 03_rprofile_gi_errs.py: FAIL
ERROR   - Unexpected errno 5, desc Class not found
ERROR   - Expected No such instance 6
ERROR   - NameError : global name 'tc' is not defined
Traceback (most recent call last):
  File "/root/cimtest/suites/libvirt-cim/lib/XenKvmLib/const.py", line 141, in do_try
    rc = f()
  File "03_rprofile_gi_errs.py", line 85, in main
    logger.error("------ FAILED: %s %s ------", cn, tc)
NameError: global name 'tc' is not defined
ERROR       - None

Turns out the profile test doesn't define/use tc. Found 2 other such
occurrances and fixed them as well.