Fix logging in 09_procrasd.py
Traceback (most recent call last):
  File "/usr/lib64/python2.7/logging/__init__.py", line 838, in emit
    msg = self.format(record)
  File "/usr/lib64/python2.7/logging/__init__.py", line 715, in format
    return fmt.format(record)
  File "/usr/lib64/python2.7/logging/__init__.py", line 464, in format
    record.message = record.getMessage()
  File "/usr/lib64/python2.7/logging/__init__.py", line 328, in
getMessage
    msg = msg % self.args
TypeError: %d format: a number is required, not NoneType

Signed-off-by: Eduardo Lima (Etrunko) <eblima@br.ibm.com>