Cimtest: Fix typo in SettingsDefine/01_forward.py
  File "01_forward.py", line 58, in setup_env
      return FAIL, cmxl
  NameError: global name 'cmxl' is not defined

It should be cxml instead of cmxl

Signed-off-by: Eduardo Lima (Etrunko) <eblima@br.ibm.com>