[TEST] Reduce the length of bridge name.
Lately I have seen this
(VirtualSystemManagementService - 06_addresource.py) test
fails with following error -

# virsh -c qemu:///system net-create /home/net.xml
error: Failed to create network from /home/net.xml
error: cannot create dummy tap device 'testbridge55-nic' to set mac address on bridge 'testbridge55': Invalid argument

Reducing the size of bridge name fixed this issue. I looked on
the net but could not find more  info on when this  behaviour
changed in libvirt.

Signed-off-by: Sharad Mishra <snmishra@us.ibm.com>